version: "3"
services: 
    server:
        build: .
        ports: 
            - "4000:3000"
        env_file: 
            - ./.env
    postgres-database:
        image: postgres
        env_file: 
            - ./postgres-db.env
        volumes:
            - postgres-db:/var/lib/postgresql/data/

volumes:
    postgres-db:

